name: Deploy to Surge

on:
  push:
    branches:
      - master

concurrency:
  group: "surge"
  cancel-in-progress: true

jobs:
  buildNdeploy:
    environment: production
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: build/
    steps:
      # fetch du code
      - name: Checkout
        uses: actions/checkout@v3
      # deploy to surge
      - name: Deploy to Surge
        run: |
          npm install -g surge
          surge ./ --domain ${{ secrets.SURGE_DOMAIN }} --token ${{ secrets.SURGE_TOKEN }}